name: ${project.name}
main: ${MainClass}
version: ${project.version}
description: ${project.description}
author: ${Author}
depend: [mcMMO]
commands:
   StatsGui:
      description: Hide or show the mcMMO stats gui.
      usage: /StatsGui [Hide|Show]